import { supabase } from '@/lib/supabase'
import type { ActivityTemplateWithContent, GroupType, TemplateTask } from '@/types'

export async function fetchActivityTemplates(): Promise<ActivityTemplateWithContent[]> {
  const [
    { data: templates },
    { data: templateGroups },
    { data: taskLinks },
    { data: tasks },
    { data: taskGroupLinks },
    { data: rewards },
  ] = await Promise.all([
    supabase.from('activity_templates').select('*').eq('is_active', true).order('sort_order'),
    supabase.from('activity_template_groups').select('*').order('sort_order'),
    supabase.from('activity_template_tasks').select('*').order('sort_order'),
    supabase.from('template_tasks').select('*').order('sort_order'),
    supabase.from('template_task_groups').select('*'),
    supabase.from('template_rewards').select('*').order('sort_order'),
  ])

  if (!templates) return []

  const tasksById = new Map((tasks ?? []).map((t) => [t.id, t]))

  const eligibleGroupsByTaskId = new Map<string, string[]>()
  for (const link of taskGroupLinks ?? []) {
    const names = eligibleGroupsByTaskId.get(link.template_task_id) ?? []
    names.push(link.group_name)
    eligibleGroupsByTaskId.set(link.template_task_id, names)
  }

  return templates.map((tmpl) => ({
    ...tmpl,
    groups: (templateGroups ?? []).filter((g) => g.activity_template_id === tmpl.id),
    tasks: (taskLinks ?? [])
      .filter((link) => link.activity_template_id === tmpl.id)
      .flatMap((link) => {
        const task = tasksById.get(link.template_task_id)
        if (!task) return []
        return [{ ...task, eligible_group_names: eligibleGroupsByTaskId.get(task.id) ?? [] } as TemplateTask]
      }),
    rewards: (rewards ?? []).filter((r) => r.activity_template_id === tmpl.id),
  }))
}

export async function applyActivityTemplate(
  eventId: string,
  template: ActivityTemplateWithContent,
): Promise<void> {
  // Step 1: Insert groups and build a name→id map
  const groupNameToId = new Map<string, string>()
  if (template.group_type === 'custom' && template.groups.length > 0) {
    const { data: insertedGroups, error } = await supabase
      .from('groups')
      .insert(template.groups.map((g) => ({ event_id: eventId, name: g.name, color: g.color })))
      .select('id, name')
    if (error) throw error
    for (const g of insertedGroups ?? []) groupNameToId.set(g.name, g.id)
  }

  // Step 2: Insert actions and build a name→id map (code is auto-generated by DB trigger)
  const actionNameToId = new Map<string, string>()
  if (template.tasks.length > 0) {
    const { data: insertedActions, error } = await supabase
      .from('actions')
      .insert(
        template.tasks.map((t) => ({
          event_id: eventId,
          name: t.name,
          points: t.points,
          description: t.description ?? null,
          max_completions: t.max_completions ?? null,
        })),
      )
      .select('id, name')
    if (error) throw error
    for (const a of insertedActions ?? []) actionNameToId.set(a.name, a.id)
  }

  // Step 3: Wire action_groups for tasks with group restrictions (empty = all groups, no rows needed)
  const actionGroupRows: { action_id: string; group_id: string }[] = []
  for (const task of template.tasks) {
    if (task.eligible_group_names.length === 0) continue
    const actionId = actionNameToId.get(task.name)
    if (!actionId) continue
    for (const groupName of task.eligible_group_names) {
      const groupId = groupNameToId.get(groupName)
      if (groupId) actionGroupRows.push({ action_id: actionId, group_id: groupId })
    }
  }
  if (actionGroupRows.length > 0) {
    const { error } = await supabase.from('action_groups').insert(actionGroupRows)
    if (error) throw error
  }

  // Step 4: Insert rewards (threshold-based, global — no reward_groups needed)
  if (template.rewards.length > 0) {
    const { error } = await supabase.from('rewards').insert(
      template.rewards.map((r) => ({
        event_id: eventId,
        name: r.name,
        required_points: r.required_points,
      })),
    )
    if (error) throw error
  }
}

export function templateGroupType(template: ActivityTemplateWithContent): GroupType {
  return template.group_type as GroupType
}
