-- Scanners + bookings board.
-- For the latest bookings-board changes (optional scanner, reset scans),
-- also run: APPLY_BOOKINGS_BOARD.sql
--
-- Base schema lives in migrations/058_scanners_bookings.sql
-- Follow-up: migrations/064_bookings_optional_scanner_reset_scans.sql
